Template for app
kmp142/SmallMattersProject pull request #1
Opened 2024-03-30 23:05 UTC by kmp142

2024-04-01 16:09 UTC, quixley requested changes
Очень большой ПР получился, от того много комментариев. В будущем прошу делать ПР поменьше. По возможности не больше 500-600 строк

2024-04-01 16:09 UTC, quixley commented on SmallMattersProject/MainTape/MainTapeView.swift
> +    private weak var controller: MainTapeViewControllerInterface?
Это лучше сделать через паттерн делегат.
1. Заводим протокол MainTapeViewDelegate, в котором нужные функции описываем (didTapAddressButton например)
2. Подписываем наш контроллер на протокол
3. Используем этот протокол вместо MainTapeViewControllerInterface
4. Переименовать controller в delegate

2024-04-01 16:09 UTC, quixley commented on SmallMattersProject/MainTape/MainTapeView.swift
> +        searchBar.addSubview(filtersButton)
лучше это вынести за пределы функции. Так как из названия функции мы не можем понять, что внутри еще и searchBar добавляет свои вьюшки

2024-04-01 16:09 UTC, quixley commented on SmallMattersProject/Map/Map with ads/MapWithAdsVC.swift
> +        DispatchQueue.main.async { [weak self] in
тут нет необходимости делать weak, тк мы сами не захватываем DispatchQueue.main

2024-04-01 16:09 UTC, quixley commented on SmallMattersProject/Map/SelectLocationMap/MapViewController.swift
> +        DispatchQueue.main.async {
тут тоже нет необходимости в main поток выводить

2024-04-01 16:09 UTC, quixley commented on SmallMattersProject/Map/SelectLocationMap/MapViewController.swift
> +        DispatchQueue.main.async { [weak self] in
тут тоже не нужно в главный принуждать

2024-04-01 16:09 UTC, quixley commented on SmallMattersProject/Map/SelectLocationMap/MapViewController.swift
> +    @objc func keyboardWillShow(notification: Notification) {
этот и метод ниже можно пометить private

2024-04-01 16:09 UTC, quixley commented on SmallMattersProject/Map/SelectLocationMap/MapViewModel.swift
> +        DispatchQueue.main.async { [weak self] in
тут не нужно main

2024-04-01 16:09 UTC, quixley commented on SmallMattersProject/Map/SelectLocationMap/MapViewModel.swift
> +        DispatchQueue.main.async { [weak self] in
И тут main убрать

2024-04-01 21:37 UTC, kmp142 commented on SmallMattersProject/MainTape/AdCVCell.swift
> +        DispatchQueue.main.async {
У меня почему-то не скругляются imageView когда не использую DispatchQueue.main.async :( В каком месте будет лучше всего выполнить скругление? Заранее не могу задать cornerRadius так-как нужно знать фреймы, чтобы скруглить до круга

2024-04-04 09:35 UTC, ironrustem commented on SmallMattersProject/Map/SelectLocationMap/SelectLocationMapViewModel.swift
> +            if !response.collection.children.isEmpty {
тут получше будет смотреть guard

2024-04-04 09:35 UTC, ironrustem commented on SmallMattersProject/Map/Yandex Service Classes/YandexMapsAddressSearchInteractor.swift
> +              print("error happened \(String(describing: error?.localizedDescription))")
тут ошибку в completion прокинуть

2024-04-04 09:35 UTC, ironrustem commented on SmallMattersProject/Map/Yandex Service Classes/YandexMapsAddressSearchInteractor.swift
> +                print("error happened \(String(describing: error?.localizedDescription))")
тут ошибку в completion прокинуть

2024-04-10 04:04 UTC, merged